# fly.toml for tweetschallenge
app = "tweetschallenge"

primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  GIN_MODE = "release"
  RATE_LIMIT_ENABLED = "true"
  RATE_LIMIT_WINDOW_SEC = "60"
  RATE_LIMIT_MAX_TWEETS = "20"
